language: python
python:
  - "3.8"

install: 
  - "pip install -r requirements/base.txt"
  - "pip install -r requirements/test.txt"

script:
  - coverage run -m pytest
  - coverage xml

after_success:
  - codecov -t $CODECOV_TOKEN